from tkinter import *
from tkinter import messagebox
def error():
    top=Toplevel()
    top.withdraw()
    messagebox.showerror("Error", "Error message")

def home():
    top = Toplevel()
    top.geometry("1350x1350+0+0")
    top.title("Home Page")
    top.configure(background='#858179')
    w = Label(top, font=('arial', 25, 'bold'), text="EVENT REGISTRATION / LOGIN / SIGNUP PAGE", fg='white', bg="black", height=2,
              width=120)
    w.pack()

    def page():
        top = Toplevel()
        top.geometry("1350x1350+0+0")
        top.configure(background='gray')
        top.title("Login Page")
        x = Label(top, font=('arial', 20, 'bold'), text="Login ", fg='white', bg="black", width='120', height='2')
        x.pack()

        def login():
            username_info = username.get()
            password_info = password.get()
            if username_info == "":
                error()
            elif password_info == "":
                error()
            else:
                Label(top, text="User login successfully", fg='black').pack()

            print("User Name:", username_info)
            print("Password:", password_info)
            username_info = str(username_info)
            password_info = str(password_info)
            file = open("login.txt", "w")
            file.write(username_info+"\n")  
            file.write(password_info+"\n")
            username_entry.delete(0, END)
            password_entry.delete(0, END)
        username_text = Label(top, text="User Name")
        password_text = Label(top, text="Password")  
        username_text.place(x=15, y=75)
        password_text.place(x=15, y=145)
        username = StringVar()
        password = StringVar()
        username_entry = Entry(top, textvariable=username, width='30')
        password_entry = Entry(top, textvariable=password, width='30')
        username_entry.place(x=15, y=105)
        password_entry.place(x=15, y=175)
        register = Button(top, text="Login", width='10', height='2', command=login)
        register.place(x=15, y=240)
        register = Button(top, text="Quit", width='10', height='2', command=top.destroy)
        register.place(x=100, y=240)

    def page1():
        top = Toplevel()
        top.geometry("1350x1350+0+0")
        top.configure(background='gray')
        top.title("Sign Up Page")
        x = Label(top, font=('arial', 20, 'bold'), text="Sign up", fg='white', bg="black", width='120', height='2')
        x.pack()

        def signup():
            firstname_info = firstname.get()
            lastname_info = lastname.get()
            emailid_info = emailid.get()
            mobno_info = mobno.get()
            if firstname_info == "":
                error()
            elif firstname_info >='a' or firstname <='z':
                pass
            if lastname_info == "":
                error()
            elif lastname_info >='a' or lastname <='z':
                pass
            elif emailid_info=="":
                error()
            elif mobno_info=="":
                error()
            else:
                Label(top,text="user Sign up successfully",fg='black').pack()
            mobno_info = str(mobno_info)
            print("First Name:", firstname_info)
            print("Last Name:", lastname_info)
            print("Email:", emailid_info)
            print("Mobile N:",mobno_info)
            file = open("signup.txt", "w")
            file.write(firstname_info+"\n")
            file.write(lastname_info+"\n")
            file.write(emailid_info+"\n")
            file.write(mobno_info+"\n")
            firstname_entry.delete(0, END)
            lastname_entry.delete(0, END)
            emailid_entry.delete(0, END)
            mobno_entry.delete(0, END)

        firstname_text = Label(top, text="First Name*")
        lastname_text = Label(top, text="Last Name*")
        emailid_text = Label(top, text="Email-Id*")
        mobno_text = Label(top, text="Mobile No*")
        firstname_text.place(x=15, y=80)
        lastname_text.place(x=15, y=150)
        emailid_text.place(x=15, y=220)
        mobno_text.place(x=15, y=290)
        firstname= StringVar()
        lastname= StringVar()
        emailid = StringVar()
        mobno= IntVar()
        firstname_entry = Entry(top, textvariable=firstname, width='30')
        lastname_entry = Entry(top, textvariable=lastname, width='30')
        emailid_entry = Entry(top, textvariable=emailid, width='30')
        mobno_entry = Entry(top, textvariable=mobno, width='30')
        firstname_entry.place(x=15, y=105)
        lastname_entry.place(x=15, y=175)
        emailid_entry.place(x=15, y=245)
        mobno_entry.place(x=15, y=315)
        register = Button(top, text="Sign Up", width='10', height='2', command=signup)
        register.place(x=15, y=380)
        register = Button(top, text="Quit", width='10', height='2', command=top.destroy)
        register.place(x=100, y=380)
    def event():
        top = Toplevel()
        top.geometry("1350x1350+0+0")
        top.title("Event")
        x = Label(top, font=('arial', 20, 'bold'), text="EVENT NAME", fg='white', bg="black", width='120', height='2')
        x.pack()
        top.configure(background='#858179')

        def save_info():
            top = Toplevel()
            top.geometry("1350x1350+0+0")
            w = Label(top, text="REGISTRATION DETAILS", font=('arial', 20, 'bold'), fg='white', bg='black', width='200',
                      height='2')
            w.pack()

            def save_page():
                firstname_info = firstname.get()
                lastname_info = lastname.get()
                mobno_info = mobno.get()
                emailid_info = emailid.get()
                address_info = address.get()
                if firstname=="":
                    error()
                elif firstname >="a" or firstname <="z":
                    pass
                if lastname =="":
                    error()
                elif lastname >="a" or lastname <="z":
                    pass
                elif emailid_info == "":
                    error()
                elif mobno_info == "":
                    error()
                elif address_info=="":
                    error()
                else:
                    Label(top, text="Registration successfully", fg='black').pack()
                mobno_info = str(mobno_info)
                print("First Name:", firstname_info)
                print("Last Name:", lastname_info)
                print("Mobile No:", mobno_info)
                print("Email:", emailid_info)
                print("Address:", address_info)
                file = open("information.txt", "w")
                file.write("first name:"+firstname_info+"\n")
                file.write("Last name:"+lastname_info+"\n")
                file.write("Mobile No:"+mobno_info+"\n")
                file.write("Email id:"+emailid_info+"\n")
                file.write("Address:"+address_info+"\n")
                firstname_entry.delete(0, END)
                lastname_entry.delete(0, END)
                mobno_entry.delete(0, END)
                emailid_entry.delete(0, END)
                address_entry.delete(0, END)

            firstname_text = Label(top, text="First Name*")
            lastname_text = Label(top, text="Last Name*")
            mobno_text = Label(top, text="Mobile No*")
            emailid_text = Label(top, text="Email*")
            address_text = Label(top, text="Address*")
            firstname_text.place(x=15, y=80)
            lastname_text.place(x=15, y=150)
            mobno_text.place(x=15, y=220)
            emailid_text.place(x=15, y=290)
            address_text.place(x=15, y=360)
            firstname = StringVar()
            lastname = StringVar()
            mobno = IntVar()
            emailid = StringVar()
            address = StringVar()
            firstname_entry = Entry(top, textvariable=firstname, width="30")
            lastname_entry = Entry(top, textvariable=lastname, width="30")
            mobno_entry = Entry(top, textvariable=mobno, width="30")
            emailid_entry = Entry(top, textvariable=emailid, width="30")
            address_entry = Entry(top, textvariable=address, width="30")
            firstname_entry.place(x=15, y=100)
            lastname_entry.place(x=15, y=170)
            mobno_entry.place(x=15, y=240)
            emailid_entry.place(x=15, y=310)
            address_entry.place(x=15, y=380)
            register = Button(top, text="Register", width='10', height='2', command=save_page)
            register.place(x=15, y=450)
            button0 = Button(top, text='QUIT', width='10',height='2', command=top.destroy)
            button0.place(x=100,y=450)

        btn0 = Button(top, text="CRICKET", fg='white', bg='black', height=2,width=42, command=save_info)
        btn0.place(x=0,y=120)
        btn0 = Button(top, text="DANCE", fg='white', bg='black', height=2,width=42, command=save_info)
        btn0.place(x=260,y=120)
        btn0 = Button(top, text="KABADDI", fg='white', bg='black', height=2,width=42, command=save_info)
        btn0.place(x=520,y=120)
        btn0 = Button(top, text="RACING", fg='white', bg='black', height=2,width=42 ,command=save_info)
        btn0.place(x=800,y=120)
        btn0 = Button(top, text='QUIT', fg='white', bg='black', height=2, width=42,command=top.destroy)
        btn0.place(x=1060,y=120)

   
    button0 = Button(top, text='Login', fg='white', bg='black', width=52,height=2 ,command=page)
    button0.place(x=0,y=120)
    button0 = Button(top, text='Sign Up', fg='white', bg='black', width=52,height=2, command=page1)
    button0.place(x=373,y=120)
    button0 = Button(top, text='EVENTS', fg='white', bg='black', width=52,height=2, command=event)
    button0.place(x=685,y=120)
    
    button0 = Button(top, text='QUIT', fg='white', bg='black', width=52,height=2 ,command=top.destroy)
    button0.place(x=990,y=120)


def about():
    top = Toplevel()
    top.geometry("1350x1350+0+0")
    top.title("About")
    top.configure(background='#858179')
    x = Label(top, font=('arial', 25, 'bold'), text="ABOUT THE APPLICATION", fg='white', bg="black", height=2, width=120)
    x.pack()
    w=Label(top,text="FEATURES :-",font=('arial',15,'bold'))
    w.place(x=15,y=140)
    w=Label(top,text="User can login here with enter their username and a password",font=('arial', 10, 'bold'))
    w.place(x=15,y=180)
    w=Label(top,text="User can signup here with enter their name , mobile number ,emailid ",font=('arial', 10, 'bold'))
    w.place(x=15,y=220)
    w=Label(top,text="User can fill his registration from for event with his full details",font=('arial', 10, 'bold'))
    w.place(x=15,y=260)
    button0 = Button(top, text='QUIT', width='10',height='1', command=top.destroy)
    button0.place(x=15,y=300)
    
   

def help():
    top = Toplevel()
    top.geometry("1350x1350+0+0")
    top.title("Help")
    top.configure(background='#858179')
    a = Label(top, font=('arial', 25, 'bold'), text="WELCOME TO HELP CENTER",
              fg='white', bg="black", height=2, width=120)
    a.pack()
    def click1():
        top=Toplevel()
        top.geometry("1350x1350+0+0")
        top.title("Welcome to Login information")
        w=Label(top,text="Login information :-",font=('arial',15,'bold'))
        w.place(x=15,y=15)
        w=Label(top,text="\n 1.Enter your username and username must conatain character as well as digit",font=('arial',10,'bold'))
        w.place(x=15,y=50)
        w = Label(top,text="2.Enter your password and password must contain character,underscore,\n any symbol as well as digit",font=('arial',10,'bold'))
        w.place(x=15, y=100)
    def click2():
        top=Toplevel()
        top.geometry("1350x1350+0+0")
        top.title("Welcome to Sign information")
        w=Label(top,text="Sign in information :-",font=('arial',15,'bold'))
        w.place(x=15,y=15)
        w=Label(top,text="\n 1.Enter your firstname and firstname must conatain character only",font=('arial',10,'bold'))
        w.place(x=15,y=50)
        w = Label(top,text="2.Enter your lastname and lastname must contain character only",font=('arial',10,'bold'))
        w.place(x=15, y=110)
        w = Label(top, text="\n 3.Enter your emailid and emailid must conatain character,symbols and digit",font=('arial',10,'bold'))
        w.place(x=15, y=140)
        w = Label(top,text="4.Enter your mob number and mob number must contain digit only",font=('arial',10,'bold'))
        w.place(x=15, y=190)
    def click3():
        top=Toplevel()
        top.geometry("1350x1350+0+0")
        top.title("Welcome to Registration information")
        w = Label(top, text="Registration information :-",font=('arial',15,'bold'))
        w.place(x=15, y=10)
        w = Label(top, text="\n 1.Enter your firstname and firstname must conatain character only",font=('arial',10,'bold'))
        w.place(x=15, y=40)
        w = Label(top, text="2.Enter your lastname and lastname must contain character only",font=('arial',10,'bold'))
        w.place(x=15, y=80)
        w = Label(top, text="3.Enter your mob number and mob number must contain digit only",font=('arial',10,'bold'))
        w.place(x=15, y=110)
        w = Label(top, text="\n 4.Enter your emailid and emailid must conatain character,symbols and digit",font=('arial',10,'bold'))
        w.place(x=15, y=128)
        w = Label(top, text="\n 5.Enter your address and address must conatain character and digit",font=('arial',10,'bold'))
        w.place(x=15, y=165)

    w=Label(top,text="1. Click here to Help about Login",font=('arial',15,'bold'))
    w.place(x=15,y=150)
    button1=Button(top,text="click",width='10',height='1',command=click1)
    button1.place(x=350,y=150)
    w = Label(top, text="2. Click here to Help about Sign in",font=('arial',15,'bold'))
    w.place(x=15, y=200)
    button2=Button(top,text="click",width='10',height='1',command=click2)
    button2.place(x=380,y=200)
    w = Label(top, text="3. Click here to Help about Registration",font=('arial',15,'bold'))
    w.place(x=15, y=250)
    button3 = Button(top, text="click",width='10',height='1',command=click3)
    button3.place(x=410, y=250)
    button3=Button(top,text="Quit",width='10',command=top.destroy)
    button3.place(x=15,y=300)
root = Tk()
root.geometry("1350x1350+0+0")
root.title("New Project")
w = Label(root, font=('arial', 25, 'bold'), text="WELCOME TO ONLINE EVENT BOOKING SYSTEM AT A CURRENT DISTRICT",
          fg='white', bg="black", height=2, width=120)
'''w = Label(root, font=('arial', 25, 'bold'), text="",
          fg='white', bg="black", height=2, width=120)'''
w.pack(side=TOP)
root.configure(background='#858179')
button1 = Button(root, text='HOME', fg='white', bg='black', height=2,width=52, command=home)
button1.place(x=0,y=120)
button2 = Button(root, text='ABOUT', fg='white', bg='black', height=2,width=52, command=about)
button2.place(x=373,y=120)
button3 = Button(root, text='HELP', fg='white', bg='black', height=2,width=52, command=help)
button3.place(x=685,y=120)
button4 = Button(root, text='QUIT', fg='white', bg='black', height=2,width=52, command=root.destroy)
button4.place(x=990,y=120)
w1 = Label(root,font=('arial',50,'bold'),text="HARDWORKING IS \n KEY TO SUCCESS",fg='white', bg='gray')
w1.place(x=350,y=450)
root.mainloop()
